version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/assessment-platform:server-latest  # Use the image from Docker Hub
    ports:
      - "5000:5000"
    env_file: 
      - /server/.env
    environment:
      - NODE_ENV=production
      - MONGO_URI=${DATABASE_URL}
    depends_on:
      - mongodb

  frontend:
    image: ${DOCKER_USERNAME}/assessment-platform:client-latest  # Use the image from Docker Hub
    ports:
      - "3000:3000"
    env_file: 
      - /client/.env

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: